### ISSUE TITLE
please help on custom assets to using image

### ISSUE THREAD

**Issue by 9to1url** [meddle0x53/blogit_web#3]
Hi Blogit,

I tried to use image in post, but not successful, like this:
* first upload the image to git repo
* in post using 
```markdown
![](abc.image)
```

I also search the source code, looks like you use this:
```elixir
  plug Plug.Static,
    at: "custom/",
    from: Blogit.RepositoryProviders.Git.local_path, gzip: false,
    only: [Application.get_env(:blogit, :assets_path, "assets")]
```

So I added "assets" folder within blogit_sample , but that not work, showing this error msg:
```
no route found for GET /custom/assets/images/metaprogramming.jpg (BlogitWeb.Web.Router)
```

Could you advise?

**Comment by meddle0x53** [comment]
Hi, it is related to `Plug.Static`, using `only` doesn't allow serving from subfolders.
See this : https://elixirforum.com/t/provide-static-path-in-plug-static/2417

So you can remove the `only` option or use `only_matching` (https://hexdocs.pm/plug/Plug.Static.html#module-options), or add to it like, for example:

```
only: [Application.get_env(:blogit, :assets_path, "assets"), Path.join(Application.get_env(:blogit, :assets_path, "assets"), "images")].
```

Hope that helps.

**Comment by 9to1url** [comment]
I tried change _only_ to _only_mathing_, that works. So any files created under folder assets-image/ can be read without issue. thanks.

**Comment by meddle0x53** [comment]
Glad that you are using BlogitWeb!
