### ISSUE TITLE
How to add image to article?

### ISSUE THREAD

**Issue by 9to1url** [meddle0x53/blogit_web#5]
I used this format but the image not showing:

```markdown
![alt text](/custom/assets-image/pic2.jpg)
```

**Comment by meddle0x53** [comment]
Try with:
```
![alt text](/custom/assets-image/pic2.jpg "some desc") {: .inline-image}
```

The library we use to parse the markdown (eamark) has its caveats.

**Comment by 9to1url** [comment]
Let me try.

**Comment by 9to1url** [comment]
It can shows, but image not fit the width, right side panel overlap portion of the image.

**Comment by meddle0x53** [comment]
The `.inline-image` is actually an example of a CSS class.
It is something like:
```
img.inline-image {
  width: 100%;
  height: auto;
}
```

But the idea is that you can define yours.

**Comment by 9to1url** [comment]
Sorry for lack of CSS knowledge. Your solution works!

**Comment by 9to1url** [comment]
solution provided, close the ticket.
